controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    system_identifier:
      type: custom_effort_controllers/SystemIdentifier

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu_sensor
    frame_id: imu_link
    # static_covariance_angular_velocity: [0.000300, -0.000051, 0.000005, -0.000051, 0.000946, 0.000026, 0.000005, 0.000026, 0.000616]
    # static_covariance_linear_acceleration: [0.006914, -0.000597, 0.000519, -0.000597, 0.003977, -0.000170, 0.000519, -0.000170, 0.003696]

mecanum_drive_controller:
  ros__parameters:
    reference_timeout: 0.9

    front_left_wheel_command_joint_name: front_left_shaft_joint
    front_right_wheel_command_joint_name: front_right_shaft_joint
    rear_left_wheel_command_joint_name: rear_left_shaft_joint
    rear_right_wheel_command_joint_name: rear_right_shaft_joint

    use_stamped_vel: false
    enable_odom_tf: false

    kinematics:
      wheels_radius: 0.04
      sum_of_robot_center_projection_on_X_Y_axis: 0.175
  
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_shaft_joint", "rear_left_shaft_joint"]
    right_wheel_names: ["front_right_shaft_joint", "rear_right_shaft_joint"]

    wheel_separation: 0.18
    wheel_radius: 0.04

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    velocity_rolling_window_size: 10

system_identifier:
  ros__parameters:
    joint: "rear_right_shaft_joint"