teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: false
    enable_turbo_button: 0
    axis_linear:
      x: 1
      y: 0
    axis_angular:
      yaw: 2

    scale_linear:
      x: 6.0
      y: 6.0
    scale_linear_turbo:
      x: 12.0
      y: 12.0

    scale_angular:
      yaw: 4.0
    scale_angular_turbo:
      yaw: 16.0

    inverted_reverse: true
    publish_stamped_twist: true

imu_feedback_node:
  ros__parameters:
    alpha: 1.0
    mid_point: 5.0