teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: false
    enable_turbo_button: 0
    axis_linear:
      x: 1
      y: 0
    axis_angular:
      yaw: 2

    scale_angular:
      yaw: 1.0
    scale_linear:
      x: 0.5
      y: 0.5
    
    scale_angular_turbo:
      yaw: 2.0
    scale_linear_turbo:
      x: 2.0
      y: 2.0

    inverted_reverse: true
    publish_stamped_twist: true

imu_feedback_node:
  ros__parameters:
    alpha: 1.0
    mid_point: 5.0