teleop_twist_joy_node:
  ros__parameters:
    frame: "base_link"
    publish_stamped_twist: true

    require_enable_button: false
    enable_turbo_button: 0
    axis_linear:
      x: 1
      y: 0
    axis_angular:
      yaw: 2

    scale_linear:
      x: 0.5
      y: 0.5
    scale_linear_turbo:
      x: 1.3823
      y: 1.3823

    scale_angular:
      yaw: 4.5
    scale_angular_turbo:
      yaw: 9.0

    inverted_reverse: true

teleop_twist_keyboard_node:
  ros__parameters:
    frame_id: "base_link"
    stamped: true

imu_feedback_node:
  ros__parameters:
    alpha: 1.0
    mid_point: 5.0

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 100.0
    robot_feedback: "OPEN_LOOP"
    max_velocity: [1.3823, 1.3823, 9.0]
    min_velocity: [-1.3823, -1.3823 , -9.0]
    max_accel: [2.5, 2.5, 13.0]
    max_decel: [-2.5, -2.5, -13.0]
    enable_stamped_cmd_vel: true